In [1]:
# Import the required modules
import pandas as pd
import numpy as np
from pathlib import Path
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

## Step 1: Read in the dataset about the current customers of the startup.

In [2]:
# Read the usage_stats.csv file from the Resources folder into a Pandas DataFrame
df = pd.read_csv(
    Path("../Project-4/NH_ProviderInfo_Aug2024.csv")
)

# Review the DataFrame
display(df.head())
display(df.tail())

CMS Certification Number (CCN)                                Provider Name  \
0                         015009                     BURNS NURSING HOME, INC.   
1                         015010               COOSA VALLEY HEALTHCARE CENTER   
2                         015012                   HIGHLANDS HEALTH AND REHAB   
3                         015014  EASTVIEW REHABILITATION & HEALTHCARE CENTER   
4                         015015                PLANTATION MANOR NURSING HOME   

              Provider Address     City/Town State  ZIP Code  \
0         701 MONROE STREET NW  RUSSELLVILLE    AL     35653   
1       260 WEST WALNUT STREET     SYLACAUGA    AL     35150   
2          380 WOODS COVE ROAD    SCOTTSBORO    AL     35768   
3     7755 FOURTH AVENUE SOUTH    BIRMINGHAM    AL     35206   
4  6450 OLD TUSCALOOSA HIGHWAY      MC CALLA    AL     35111   

   Telephone Number  Provider SSA County Code County/Parish  \
0        2563324110                       290      Franklin   
1        2562495604                       600     Talladega   
2        2562183708                       350       Jackson   
3        2058330146                       360     Jefferson   
4        2054776161                       360     Jefferson   

             Ownership Type  ...  \
0  For profit - Corporation  ...   
1  For profit - Corporation  ...   
2       Government - County  ...   
3   For profit - Individual  ...   
4   For profit - Individual  ...   

   Number of Citations from Infection Control Inspections  Number of Fines  \
0                                                NaN                     2   
1                                                0.0                     0   
2                                                NaN                     0   
3                                                0.0                     0   
4                                                NaN                     0   

   Total Amount of Fines in Dollars Number of Payment Denials  \
0                          24644.14                         0   
1                              0.00                         0   
2                              0.00                         0   
3                              0.00                         0   
4                              0.00                         0   

  Total Number of Penalties                                       Location  \
0                         2     701 MONROE STREET NW,RUSSELLVILLE,AL,35653   
1                         0      260 WEST WALNUT STREET,SYLACAUGA,AL,35150   
2                         0        380 WOODS COVE ROAD,SCOTTSBORO,AL,35768   
3                         0   7755 FOURTH AVENUE SOUTH,BIRMINGHAM,AL,35206   
4                         0  6450 OLD TUSCALOOSA HIGHWAY,MC CALLA,AL,35111   

  Latitude Longitude  Geocoding Footnote Processing Date  
0  34.5149   -87.736                 NaN      2024-08-01  
1  33.1637   -86.254                 NaN      2024-08-01  
2  34.6611   -86.047                 NaN      2024-08-01  
3  33.5595   -86.722                 NaN      2024-08-01  
4  33.3221   -87.034                 NaN      2024-08-01  

[5 rows x 103 columns]

CMS Certification Number (CCN)  \
14820                         745021   
14821                         745022   
14822                         745038   
14823                         745039   
14824                         745040   

                                       Provider Name         Provider Address  \
14820                  LINDALE SPECIALTY CARE CENTER            13905 FM 2710   
14821                      WARE MEMORIAL CARE CENTER    1510 S. VAN BUREN ST.   
14822  TIERRA ESTE NURSING AND REHABILITATION CENTER  14300 PEBBLE HILLS BLVD   
14823              MIDTOWNE MEADOWS HEALTH AND REHAB            110 DYLAN WAY   
14824                  THE SARAH ROBERTS FRENCH HOME           1315 TEXAS AVE   

         City/Town State  ZIP Code  Telephone Number  \
14820      LINDALE    TX     75771        4302602300   
14821     AMARILLO    TX     79101        8063730471   
14822      EL PASO    TX     79938        9159559998   
14823   MIDLOTHIAN    TX     76065              1111   
14824  SAN ANTONIO    TX     78201        2107364238   

       Provider SSA County Code County/Parish  \
14820                       892         Smith   
14821                       860        Potter   
14822                       480       El Paso   
14823                       470         Ellis   
14824                       130         Bexar   

                               Ownership Type  ...  \
14820  For profit - Limited Liability company  ...   
14821                For profit - Corporation  ...   
14822                For profit - Corporation  ...   
14823  For profit - Limited Liability company  ...   
14824                Non profit - Corporation  ...   

       Number of Citations from Infection Control Inspections  \
14820                                                NaN        
14821                                                NaN        
14822                                                NaN        
14823                                                NaN        
14824                                                NaN        

       Number of Fines  Total Amount of Fines in Dollars  \
14820                3                         367971.50   
14821                0                              0.00   
14822                7                          31595.67   
14823                5                          20013.32   
14824                7                          35733.13   

      Number of Payment Denials Total Number of Penalties  \
14820                         0                         3   
14821                         0                         0   
14822                         0                         7   
14823                         0                         5   
14824                         0                         7   

                                       Location Latitude Longitude  \
14820            13905 FM 2710,LINDALE,TX,75771  32.5191   -95.398   
14821   1510 S. VAN BUREN ST.,AMARILLO,TX,79101  35.1987  -101.842   
14822  14300 PEBBLE HILLS BLVD,EL PASO,TX,79938  31.7822  -106.230   
14823         110 DYLAN WAY,MIDLOTHIAN,TX,76065  32.4783   -96.982   
14824       1315 TEXAS AVE,SAN ANTONIO,TX,78201  29.4494   -98.534   

       Geocoding Footnote Processing Date  
14820                 NaN      2024-08-01  
14821                 NaN      2024-08-01  
14822                 NaN      2024-08-01  
14823                22.0      2024-08-01  
14824                 NaN      2024-08-01  

[5 rows x 103 columns]

In [3]:
# Create new dataframe with only necessary columns
df_clean = df[['Overall Rating',
               'Ownership Type',
               'Provider Type',
               'Number of Certified Beds',
               'Average Number of Residents per Day',
               'Adjusted Total Nurse Staffing Hours per Resident per Day',
               'Adjusted RN Staffing Hours per Resident per Day',
               'Adjusted Nurse Aide Staffing Hours per Resident per Day',
               'Adjusted LPN Staffing Hours per Resident per Day',
               'Health Inspection Rating',
               'Number of Citations from Infection Control Inspections',
               'Number of Fines',
               'Total Amount of Fines in Dollars',
               'Total Number of Penalties']]
                    

display(df_clean.head())

Overall Rating            Ownership Type          Provider Type  \
0             2.0  For profit - Corporation  Medicare and Medicaid   
1             4.0  For profit - Corporation  Medicare and Medicaid   
2             4.0       Government - County  Medicare and Medicaid   
3             2.0   For profit - Individual  Medicare and Medicaid   
4             2.0   For profit - Individual  Medicare and Medicaid   

   Number of Certified Beds  Average Number of Residents per Day  \
0                        57                                 50.0   
1                        85                                 76.9   
2                        50                                 45.1   
3                        92                                 76.9   
4                       103                                 86.6   

   Adjusted Total Nurse Staffing Hours per Resident per Day  \
0                                            4.35288          
1                                            4.34347          
2                                            4.62367          
3                                            3.23306          
4                                            4.22637          

   Adjusted RN Staffing Hours per Resident per Day  \
0                                          1.31700   
1                                          0.89213   
2                                          1.08882   
3                                          0.59689   
4                                          0.50214   

   Adjusted Nurse Aide Staffing Hours per Resident per Day  \
0                                            2.60798         
1                                            2.60828         
2                                            2.93756         
3                                            1.76798         
4                                            2.63787         

   Adjusted LPN Staffing Hours per Resident per Day  Health Inspection Rating  \
0                                           0.42789                       2.0   
1                                           0.84306                       4.0   
2                                           0.59729                       4.0   
3                                           0.86819                       3.0   
4                                           1.08637                       2.0   

   Number of Citations from Infection Control Inspections  Number of Fines  \
0                                                NaN                     2   
1                                                0.0                     0   
2                                                NaN                     0   
3                                                0.0                     0   
4                                                NaN                     0   

   Total Amount of Fines in Dollars  Total Number of Penalties  
0                          24644.14                          2  
1                              0.00                          0  
2                              0.00                          0  
3                              0.00                          0  
4                              0.00                          0

In [4]:
# Remove NaN Rows
df_cleaned = df_clean.dropna()

In [5]:
# Column Names to Use
column_names = ['Overall Rating',
                'Number of Certified Beds',
                'Average Number of Residents per Day',
                'Adjusted Total Nurse Staffing Hours per Resident per Day',
                'Adjusted RN Staffing Hours per Resident per Day',
                'Adjusted Nurse Aide Staffing Hours per Resident per Day',
                'Adjusted LPN Staffing Hours per Resident per Day',
                'Health Inspection Rating',
                'Number of Citations from Infection Control Inspections',
                'Number of Fines',
                'Total Amount of Fines in Dollars',
                'Total Number of Penalties']

# # Scaling the numeric columns
# data_scaled = StandardScaler().fit_transform(df_cleaned[column_names])

# # Creating a DataFrame with the scaled data
# df_scaled_transformed = pd.DataFrame(data_scaled, columns=column_names)

# # Display sample data
# df_scaled_transformed.head()

In [6]:
df_numerical = df_cleaned[column_names]

df_numerical.head()

Overall Rating  Number of Certified Beds  \
1              4.0                        85   
3              2.0                        92   
9              1.0                       121   
12             2.0                       154   
13             3.0                        78   

    Average Number of Residents per Day  \
1                                  76.9   
3                                  76.9   
9                                 116.5   
12                                128.5   
13                                 75.3   

    Adjusted Total Nurse Staffing Hours per Resident per Day  \
1                                             4.34347          
3                                             3.23306          
9                                             3.96928          
12                                            3.61450          
13                                            4.32665          

    Adjusted RN Staffing Hours per Resident per Day  \
1                                           0.89213   
3                                           0.59689   
9                                           0.26906   
12                                          0.52457   
13                                          0.57203   

    Adjusted Nurse Aide Staffing Hours per Resident per Day  \
1                                             2.60828         
3                                             1.76798         
9                                             2.84637         
12                                            2.30828         
13                                            3.09326         

    Adjusted LPN Staffing Hours per Resident per Day  \
1                                            0.84306   
3                                            0.86819   
9                                            0.85385   
12                                           0.78165   
13                                           0.66137   

    Health Inspection Rating  \
1                        4.0   
3                        3.0   
9                        1.0   
12                       1.0   
13                       3.0   

    Number of Citations from Infection Control Inspections  Number of Fines  \
1                                                 0.0                     0   
3                                                 0.0                     0   
9                                                 0.0                     0   
12                                                0.0                     1   
13                                                0.0                     0   

    Total Amount of Fines in Dollars  Total Number of Penalties  
1                               0.00                          0  
3                               0.00                          0  
9                               0.00                          0  
12                          10065.25                          1  
13                              0.00                          0

In [7]:
#Transform Catagorical Columns
df_owner = pd.get_dummies(df_cleaned["Ownership Type"], dtype=np.int64)

df_owner.head()

For profit - Corporation  For profit - Individual  \
1                          1                        0   
3                          0                        1   
9                          1                        0   
12                         1                        0   
13                         0                        0   

    For profit - Limited Liability company  For profit - Partnership  \
1                                        0                         0   
3                                        0                         0   
9                                        0                         0   
12                                       0                         0   
13                                       1                         0   

    Government - City  Government - City/county  Government - County  \
1                   0                         0                    0   
3                   0                         0                    0   
9                   0                         0                    0   
12                  0                         0                    0   
13                  0                         0                    0   

    Government - Federal  Government - Hospital district  Government - State  \
1                      0                               0                   0   
3                      0                               0                   0   
9                      0                               0                   0   
12                     0                               0                   0   
13                     0                               0                   0   

    Non profit - Church related  Non profit - Corporation  Non profit - Other  
1                             0                         0                   0  
3                             0                         0                   0  
9                             0                         0                   0  
12                            0                         0                   0  
13                            0                         0                   0

In [8]:
#Transform Catagorical Columns
df_provider = pd.get_dummies(df_cleaned["Provider Type"], dtype=np.int64)

df_provider.head()

Medicaid  Medicare  Medicare and Medicaid
1          0         0                      1
3          0         0                      1
9          0         0                      1
12         0         0                      1
13         0         0                      1

In [9]:
# Concatenate Numerical and Categorical Columns
df_transformed = pd.concat([df_numerical, df_owner, df_provider], axis=1)

# Display Table
df_transformed.head()

Overall Rating  Number of Certified Beds  \
1              4.0                        85   
3              2.0                        92   
9              1.0                       121   
12             2.0                       154   
13             3.0                        78   

    Average Number of Residents per Day  \
1                                  76.9   
3                                  76.9   
9                                 116.5   
12                                128.5   
13                                 75.3   

    Adjusted Total Nurse Staffing Hours per Resident per Day  \
1                                             4.34347          
3                                             3.23306          
9                                             3.96928          
12                                            3.61450          
13                                            4.32665          

    Adjusted RN Staffing Hours per Resident per Day  \
1                                           0.89213   
3                                           0.59689   
9                                           0.26906   
12                                          0.52457   
13                                          0.57203   

    Adjusted Nurse Aide Staffing Hours per Resident per Day  \
1                                             2.60828         
3                                             1.76798         
9                                             2.84637         
12                                            2.30828         
13                                            3.09326         

    Adjusted LPN Staffing Hours per Resident per Day  \
1                                            0.84306   
3                                            0.86819   
9                                            0.85385   
12                                           0.78165   
13                                           0.66137   

    Health Inspection Rating  \
1                        4.0   
3                        3.0   
9                        1.0   
12                       1.0   
13                       3.0   

    Number of Citations from Infection Control Inspections  Number of Fines  \
1                                                 0.0                     0   
3                                                 0.0                     0   
9                                                 0.0                     0   
12                                                0.0                     1   
13                                                0.0                     0   

    ...  Government - County  Government - Federal  \
1   ...                    0                     0   
3   ...                    0                     0   
9   ...                    0                     0   
12  ...                    0                     0   
13  ...                    0                     0   

    Government - Hospital district  Government - State  \
1                                0                   0   
3                                0                   0   
9                                0                   0   
12                               0                   0   
13                               0                   0   

    Non profit - Church related  Non profit - Corporation  Non profit - Other  \
1                             0                         0                   0   
3                             0                         0                   0   
9                             0                         0                   0   
12                            0                         0                   0   
13                            0                         0                   0   

    Medicaid  Medicare  Medicare and Medicaid  
1          0         0                      1  
3          0         0                      1  
9          0         0                      1  
12 

In [10]:
# Remove NaN Rows
df_transformed_drop = df_transformed.dropna()

df_transformed_drop.head()

Overall Rating  Number of Certified Beds  \
1              4.0                        85   
3              2.0                        92   
9              1.0                       121   
12             2.0                       154   
13             3.0                        78   

    Average Number of Residents per Day  \
1                                  76.9   
3                                  76.9   
9                                 116.5   
12                                128.5   
13                                 75.3   

    Adjusted Total Nurse Staffing Hours per Resident per Day  \
1                                             4.34347          
3                                             3.23306          
9                                             3.96928          
12                                            3.61450          
13                                            4.32665          

    Adjusted RN Staffing Hours per Resident per Day  \
1                                           0.89213   
3                                           0.59689   
9                                           0.26906   
12                                          0.52457   
13                                          0.57203   

    Adjusted Nurse Aide Staffing Hours per Resident per Day  \
1                                             2.60828         
3                                             1.76798         
9                                             2.84637         
12                                            2.30828         
13                                            3.09326         

    Adjusted LPN Staffing Hours per Resident per Day  \
1                                            0.84306   
3                                            0.86819   
9                                            0.85385   
12                                           0.78165   
13                                           0.66137   

    Health Inspection Rating  \
1                        4.0   
3                        3.0   
9                        1.0   
12                       1.0   
13                       3.0   

    Number of Citations from Infection Control Inspections  Number of Fines  \
1                                                 0.0                     0   
3                                                 0.0                     0   
9                                                 0.0                     0   
12                                                0.0                     1   
13                                                0.0                     0   

    ...  Government - County  Government - Federal  \
1   ...                    0                     0   
3   ...                    0                     0   
9   ...                    0                     0   
12  ...                    0                     0   
13  ...                    0                     0   

    Government - Hospital district  Government - State  \
1                                0                   0   
3                                0                   0   
9                                0                   0   
12                               0                   0   
13                               0                   0   

    Non profit - Church related  Non profit - Corporation  Non profit - Other  \
1                             0                         0                   0   
3                             0                         0                   0   
9                             0                         0                   0   
12                            0                         0                   0   
13                            0                         0                   0   

    Medicaid  Medicare  Medicare and Medicaid  
1          0         0                      1  
3          0         0                      1  
9          0         0                      1  
12 

## Step 2: Split the data into X and y and then into testing and training sets.

In [11]:
# Split the data into X (features) and y (target)
# The y variable should focus on the target column
y = df_transformed_drop['Overall Rating']

# The X variable should include all features except the target
X = df_transformed_drop.drop(columns=['Overall Rating'])


In [12]:
# Split into testing and training sets using train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y)

## Step 3: Fit a logistic regression classifier.

In [13]:
# Declare a logistic regression model.
# Apply a random_state of 9 to the model
logistic_regression_model = LogisticRegression(solver='saga', max_iter=1000)

# Fit and save the logistic regression model using the training data
lr_model = logistic_regression_model.fit(X_train, y_train)

c:\Users\jrhay\anaconda3\envs\dev\lib\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


## Step 4: Create the predicted values for the testing and the training data.

In [14]:
#Generate training predictions
training_predictions = lr_model.predict(X_train)

#Generate testing predictions
testing_predictions = logistic_regression_model.predict(X_test)


## Step 5: Print a confusion matrix for the training data.

In [15]:
# Import the model for sklearn confusion matrix
from sklearn.metrics import confusion_matrix

# Create and save the confusion matrix for the training data
training_matrix = confusion_matrix(y_train, training_predictions)

# Print the confusion matrix for the training data
print(training_matrix)

[[1408   33  154    0    0]
 [1023   53  300    0    0]
 [ 657   64  436    0    0]
 [ 409   64  479    0    0]
 [ 234   79  565    0    0]]


## Step 6: Print a confusion matrix for the testing data.

In [16]:
# Create and save the confusion matrix for the testing data
test_matrix = confusion_matrix(y_test, testing_predictions)

# Print the confusion matrix for the testing data
print(test_matrix)

[[485  11  38   0   0]
 [360  21 108   0   0]
 [238  19 133   0   0]
 [141  21 128   0   0]
 [ 79  22 182   0   0]]


## Step 7: Print the training classification report.

In [17]:
# Create and save the training classification report
training_report = classification_report(y_train, training_predictions)

# Print the training classification report
print(training_report)

              precision    recall  f1-score   support

         1.0       0.38      0.88      0.53      1595
         2.0       0.18      0.04      0.06      1376
         3.0       0.23      0.38      0.28      1157
         4.0       0.00      0.00      0.00       952
         5.0       0.00      0.00      0.00       878

    accuracy                           0.32      5958
   macro avg       0.16      0.26      0.17      5958
weighted avg       0.19      0.32      0.21      5958



c:\Users\jrhay\anaconda3\envs\dev\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\jrhay\anaconda3\envs\dev\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\jrhay\anaconda3\envs\dev\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


## Step 8: Print the testing classification report.

In [18]:
# Create and save the testing classification report
testing_report = classification_report(y_test, testing_predictions)

# Print the testing classification report
print(testing_report)

              precision    recall  f1-score   support

         1.0       0.37      0.91      0.53       534
         2.0       0.22      0.04      0.07       489
         3.0       0.23      0.34      0.27       390
         4.0       0.00      0.00      0.00       290
         5.0       0.00      0.00      0.00       283

    accuracy                           0.32      1986
   macro avg       0.16      0.26      0.17      1986
weighted avg       0.20      0.32      0.21      1986



c:\Users\jrhay\anaconda3\envs\dev\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\jrhay\anaconda3\envs\dev\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\jrhay\anaconda3\envs\dev\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


## Step 9: Answer the following question

> **Question**: How does the performance of the training and test dataset compare?

> **Sample Answer**: Looking at the two classification reports for the training and test data, it looks as if model performance declined--albeit slightly--on the test data. This is to be expected: this is how well the model is performing on data that the model hasn't seen before. If we're still getting strong precision and recall on the test dataset, this is a good indication about how well the model is likely to perform in real life.